[package]
name = "fq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "fq"

[lib]
name = "fq"

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
nom = "7"
regex = "1.8"
